- name: '1'
  first_id: 0
  markers_x: 2
  markers_y: 2
  marker_size: 0.0742
  separation: 0.0248
  frame_at_center: true
- name: '2'
  first_id: 4
  markers_x: 2
  markers_y: 2
  marker_size: 0.0742
  separation: 0.0248
  frame_at_center: true
- name: '3'
  first_id: 8
  markers_x: 2
  markers_y: 2
  marker_size: 0.0742
  separation: 0.0248
  frame_at_center: true
- name: '4'
  first_id: 12
  markers_x: 2
  markers_y: 2
  marker_size: 0.0742
  separation: 0.0248
  frame_at_center: true