name: CI-Humble

on:
  workflow_dispatch:
  push:
    branches:
      - humble
  pull_request:
    branches:
      - humble

env:
 ROS_DISTRO: humble

jobs:
  industrial_ci:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ROS_REPO: [testing, main]
    env:
      ROS_REPO: ${{ matrix.ROS_REPO }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Source tests
        uses: "ros-industrial/industrial_ci@master"
<<<<<<< HEAD:.github/workflows/ci-humble.yml

  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    container:
      image: ros:humble
    strategy:
      fail-fast: false
      matrix:
        linter: [copyright, lint_cmake, uncrustify, xmllint]
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/action-ros-lint@v0.1
        with:
          distribution: humble
          linter: ${{ matrix.linter }}
          package-name: |
            aruco_opencv
            aruco_opencv_msgs
=======
>>>>>>> f5fdf40 (Add ament_lint tests to cmakelists instead of github workflows (#7)):.github/workflows/ci-rolling.yml
